# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# Trun off email notifications
notifications:
  email: false


os:
  - linux
  - osx

env:
  - PYTHON_VERSION="2.7"
  - PYTHON_VERSION="3.4"
  - PYTHON_VERSION="3.5"

# commands to install ulmo
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      OS_VERSION="Linux";
    else
      OS_VERSION="MacOSX";
    fi
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-${OS_VERSION}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS_VERSION}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create ulmo venv and install deps
  - conda create -q -c conda-forge --chan-pri -n test-environment python=$PYTHON_VERSION appdirs beautifulsoup4 future geojson isodate lxml mock numpy pandas pytables pytest requests suds-jurko freezegun html5lib=0.999
  - source activate test-environment
  - conda install pip
  - pip install httpretty==0.8.10
  - pip install coveralls
  - python setup.py install

# command to run tests
script:
  coverage run --source=ulmo setup.py test

# generate test coverage information
after_success:
  coveralls
